GLOBAL_SSH_PASS="b49w527526"
N1_EN="ON"; N1_NAME="Bukit Siput"; N1_USER="mk"; N1_API="3B4WHorBvlxRYipq7P4xL0TcBiF_SiBaqY8yhN9v3pwk55Ea"
N2_EN="ON"; N2_NAME="Jalan Tepi Paya"; N2_USER="mk"; N2_API="3B4X38XFU14B7z7Yo8xt1zleNTL_2ETZ7dmdfouL3C4h4gThg"
V1_EN="ON"; V1_NAME="Rechner Waltraud"; V1_USER="mk"; V1_IP="192.168.2.53"; V1_BRIDGE="WARP"; V1_PRIV="fritz"
V2_EN="ON"; V2_NAME="Rechner Bernd"; V2_USER="mk"; V2_IP="192.168.2.50"; V2_BRIDGE="WARP"; V2_PRIV="fritz"
V3_EN="ON"; V3_NAME="Rechner Alt"; V3_USER="mk"; V3_IP="192.168.2.51"; V3_BRIDGE="WARP"; V3_PRIV="fritz"
D1_EN="OFF"; D1_NAME="Desktop"; D1_USER="mk"; D1_HOST="home-nw-sgp.freeddns.org"; D1_PORT="10500"
D2_EN="OFF"; D2_NAME="SFF Ryzen9600"; D2_USER="mk"; D2_HOST="home-nw-sgp.freeddns.org"; D2_PORT="10600"
